spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/golfscore}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_OIDC_ISSUER_URI:}

server:
  port: 8080
